"""Frozen, distinct short prompts; every concurrency uses this ordered prefix."""

PROMPTS = [
    ("binary_search", "Write Python binary search for a sorted integer list, returning the matching index or -1, and explain its invariant:"),
    ("causal_inference", "Explain how a randomized controlled experiment distinguishes causation from correlation, using a concrete example:"),
    ("breadth_first_path", "Implement a shortest path search in an unweighted graph using Python and a queue, with an example:"),
    ("query_plans", "Explain when a database optimizer should choose an index scan instead of a full table scan:"),
    ("lru_cache", "Implement a small Python LRU cache with get and put operations, and explain how eviction works:"),
    ("confidence_interval", "Explain how to interpret a confidence interval for a population mean, including a common misconception:"),
    ("moving_average", "Write Python code that maintains a moving average over the latest five values of an incoming stream:"),
    ("attention_mask", "Explain why a causal attention mask is needed when a transformer predicts the next token:"),
    ("quoted_csv", "Write a Python CSV line parser that handles commas inside quoted fields and doubled quotation marks:"),
    ("eventual_consistency", "Explain eventual consistency with two replicated counters, including what a reader may observe during replication:"),
    ("merge_intervals", "Write Python code to merge overlapping closed intervals, and explain the sorting and merging steps:"),
    ("catalysis", "Explain how a catalyst changes reaction rates and why it does not change chemical equilibrium:"),
    ("async_timeout", "Show Python asyncio code that runs two independent operations with a timeout and cleans up cancelled tasks:"),
    ("differential_privacy", "Explain why adding calibrated noise to aggregate statistics can protect individual privacy, with an example:"),
    ("circular_buffer", "Implement a fixed capacity circular buffer in Python and explain how its read and write indices wrap:"),
    ("spectroscopy", "Explain how an astronomical spectrum reveals the chemical composition and motion of a distant star:"),
    ("normalize_path", "Write Python code to normalize an absolute POSIX path containing dot and parent segments without accessing the filesystem:"),
    ("stellar_remnants", "Compare a white dwarf and a neutron star in terms of formation, density, and the pressure supporting them:"),
    ("union_find", "Implement union find in Python with path compression and union by size, then explain its operations:"),
    ("benchmark_design", "Explain how to design a fair software benchmark that separates warmup cost from steady state performance:"),
    ("token_bucket", "Implement a token bucket rate limiter using a monotonic clock and explain how bursts are bounded:"),
    ("dns_caching", "Explain how DNS cache lifetimes affect lookup latency and the propagation of changed records:"),
    ("directed_cycle", "Write Python code to detect a cycle in a directed graph using depth first search and node states:"),
    ("bayesian_coin", "Explain Bayesian updating for an unknown coin bias after observing heads and tails, using a simple prior:"),
    ("decimal_rounding", "Show Python Decimal code for adding prices and applying round half even to the final currency amount:"),
    ("learning_rate", "Explain how the learning rate affects gradient descent on a quadratic function, including divergence and slow convergence:"),
    ("reservoir_sampling", "Write Python reservoir sampling that selects one uniformly random item from a stream of unknown length:"),
    ("photosynthesis", "Explain how the light reactions and Calvin cycle cooperate during photosynthesis, including their energy carriers:"),
    ("retry_backoff", "Write Python retry logic with capped exponential backoff and jitter, distinguishing retryable from permanent failures:"),
    ("statistical_power", "Explain statistical power in an A/B experiment and how sample size and effect size change it:"),
    ("json_lines", "Write Python code to read JSON Lines records and group valid numeric measurements by sensor identifier:"),
    ("compression", "Compare lossless and lossy compression, explaining why their tradeoffs differ for source code and photographs:"),
]
